#!/bin/bash

# CMS general setup

if [ "$1" == "sw" ]; then
   echo "CMS software environment"
   source /cvmfs/cms.cern.ch/cmsset_default.sh
   export SCRAM_ARCH=slc6_amd64_gcc530
elif [ "$1" == "crab2" ]; then
   echo "CRAB2 configuration"
   source /cvmfs/cms.cern.ch/crab/crab.sh
elif [ "$1" == "crab3" ]; then
   echo "CRAB3 configuration"
   source /cvmfs/cms.cern.ch/crab3/crab.sh
elif [ "$1" == "go" ]; then
   echo "Working environment"
   source /cvmfs/cms.cern.ch/cmsset_default.sh
   export SCRAM_ARCH=slc6_amd64_gcc530
   cd $GUTCODEDIR/CMSSW_8_0_5/src
   cmsenv
   source /cvmfs/cms.cern.ch/crab3/crab.sh
   cd
elif [ "$1" == "spark" ]; then
    source /cvmfs/sft.cern.ch/lcg/views/dev3/latest/x86_64-slc6-gcc49-opt/setup.sh
    source /cvmfs/sft.cern.ch/lcg/etc/hadoop-confext/hadoop-setconf.sh analytix
    export KRB5CCNAME=FILE:/tmp/gutsche_krb
    # source /cvmfs/sft.cern.ch/lcg/views/dev3/Tue/x86_64-slc6-gcc49-opt/setup.sh
   # source /afs/cern.ch/work/v/vkhriste/public/spark-root-testdata/hadoop-confext/hadoop-setconf.sh analytix
   # unset PYSPARK_PYTHON
   # unset PYSPARK_DRIVER_PYTHON
   # export PYTHONPATH=$PYTHONPATH:/afs/cern.ch/user/v/vkhriste/public/histogrammar-1.0.6
elif [ "$1" == "jupyter" ]; then
   export PYSPARK_DRIVER_PYTHON=/cvmfs/sft-nightlies.cern.ch/lcg/views/dev3/Tue/x86_64-slc6-gcc49-opt/bin/jupyter-notebook
   export PYSPARK_DRIVER_PYTHON_OPTS="--ip=`hostname` --browser='/dev/null' --port=8888"
   pyspark --packages org.diana-hep:spark-root_2.11:0.1.7 --conf spark.dynamicAllocation.enabled=false --executor-cores 4 --num-executors 60 --master yarn --py-files /afs/cern.ch/user/v/vkhriste/public/histogrammar-1.0.6.zip
else
   echo "Please give configuration"
fi
