#!/bin/bash

# CMS general setup

if [ "$1" == "sw" ]; then
   echo "CMS software environment"
   source /cvmfs/cms.cern.ch/cmsset_default.sh
   export SCRAM_ARCH=slc6_amd64_gcc491
elif [ "$1" == "crab2" ]; then
   echo "CRAB2 configuration"
   source /cvmfs/cms.cern.ch/crab/crab.sh
elif [ "$1" == "crab3" ]; then
   echo "CRAB3 configuration"
   source /cvmfs/cms.cern.ch/crab3/crab.sh
elif [ "$1" == "go" ]; then
   echo "Working environment"
   source /cvmfs/cms.cern.ch/cmsset_default.sh
   export SCRAM_ARCH=slc6_amd64_gcc491
   source /cvmfs/cms.cern.ch/crab/crab.sh
   cd $GUTCODEDIR/CMSSW_7_4_7/src
   cmsenv
   cd
else
   echo "Please give configuration"
fi
