{
 "title": "Housenet Monitoring",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "name" },
  {
   "title": "Server: CPU",
   "type": "gauge",
   "description": "Server: Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=~\"192.168.96.40:9100\",job=~\"node\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"192.168.96.40:9100\",job=~\"node\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=~\"192.168.96.40:9100\",job=~\"node\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Server: GPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "targets": [
    {
     "expr": "sum(nvidia_gpu_duty_cycle) / sum(nvidia_gpu_num_devices)"
    }
   ]
  },
  {
   "title": "Pi-Hole: CPU Busy",
   "type": "gauge",
   "description": "Pi-Hole: Busy",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=~\"192.168.96.55:9100\",job=~\"node\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"192.168.96.55:9100\",job=~\"node\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=~\"192.168.96.55:9100\",job=~\"node\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Downstairs Camera: CPU Busy",
   "type": "gauge",
   "description": "Downstairs Camera: CPU",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=~\"192.168.96.70:9100\",job=~\"node\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"192.168.96.70:9100\",job=~\"node\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=~\"192.168.96.70:9100\",job=~\"node\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Garage Camera: CPU Busy",
   "type": "gauge",
   "description": "Garage Camera: CPU",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=~\"192.168.96.65:9100\",job=~\"node\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"192.168.96.65:9100\",job=~\"node\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=~\"192.168.96.65:9100\",job=~\"node\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Upstairs Camera: CPU",
   "type": "gauge",
   "description": "Garage Camera: CPU",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 1 },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=~\"192.168.96.60:9100\",job=~\"node\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"192.168.96.60:9100\",job=~\"node\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=~\"192.168.96.60:9100\",job=~\"node\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Server: CPU Temp",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "avg(node_hwmon_temp_celsius{instance=~\"192.168.96.40:9100\",job=~\"node\",chip=~\"platform_coretemp_0\",sensor=~\"temp2|temp3|temp4|temp5\"})",
     "legendFormat": "Average Core Temperature"
    }
   ]
  },
  {
   "title": "Server: GPU Temp",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 5 },
   "targets": [
    { "expr": "nvidia_gpu_temperature_celsius", "legendFormat": "gpu{{minor_number}}" }
   ]
  },
  {
   "title": "Pi-Hole: CPU Temp",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 5 },
   "targets": [
    {
     "expr": "rpi_cpu_temperature_celsius{instance=~\"192.168.96.55:9243\"}",
     "legendFormat": "Average Core Temperature"
    }
   ]
  },
  {
   "title": "Downstairs Camera: CPU Temp",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 5 },
   "targets": [
    {
     "expr": "rpi_cpu_temperature_celsius{instance=~\"192.168.96.70:9243\"}",
     "legendFormat": "Average Core Temperature"
    }
   ]
  },
  {
   "title": "Garage Camera: CPU Temp",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 5 },
   "targets": [
    {
     "expr": "rpi_cpu_temperature_celsius{instance=~\"192.168.96.65:9243\"}",
     "legendFormat": "Average Core Temperature"
    }
   ]
  },
  {
   "title": "Upstairs Camera: CPU Temp",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 5 },
   "targets": [
    {
     "expr": "rpi_cpu_temperature_celsius{instance=~\"192.168.96.60:9243\"}",
     "legendFormat": "Average Core Temperature"
    }
   ]
  },
  {
   "title": "Server: CPU Fan",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "node_hwmon_fan_rpm{instance=~\"192.168.96.40:9100\",job=~\"node\",sensor=~\"fan1\"}",
     "legendFormat": "CPU Fan"
    }
   ]
  },
  {
   "title": "Server: GPU Fan",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 9 },
   "targets": [
    { "expr": "nvidia_gpu_fanspeed_percent", "legendFormat": "gpu{{minor_number}}" }
   ]
  },
  { "title": "Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "CPU Basic",
   "type": "graph",
   "description": "Basic CPU info",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"system\",instance=~\"192.168.96.40:9100\",job=~\"node\"}[5m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='user',instance=~\"192.168.96.40:9100\",job=~\"node\"}[5m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='iowait',instance=~\"192.168.96.40:9100\",job=~\"node\"}[5m])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=~\".*irq\",instance=~\"192.168.96.40:9100\",job=~\"node\"}[5m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (irate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=~\"192.168.96.40:9100\",job=~\"node\"}[5m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"192.168.96.40:9100\",job=~\"node\"}[5m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "CPU: Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 14 },
   "yaxes": [
    { "format": "celsius", "label": "Temperature" }
   ],
   "targets": [
    {
     "expr": "avg(node_hwmon_temp_celsius{instance=~\"192.168.96.40:9100\",job=~\"node\",chip=~\"platform_coretemp_0\",sensor=~\"temp2|temp3|temp4|temp5\"})",
     "legendFormat": "Average Core Temperature"
    },
    {
     "expr": "avg(node_hwmon_temp_crit_celsius{instance=~\"192.168.96.40:9100\",job=~\"node\",chip=~\"platform_coretemp_0\",sensor=~\"temp2|temp3|temp4|temp5\"})",
     "legendFormat": "Critical Core Temperature"
    }
   ]
  },
  {
   "title": "CPU Fan",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "none", "label": "RPM" }
   ],
   "targets": [
    {
     "expr": "node_hwmon_fan_rpm{instance=~\"192.168.96.40:9100\",job=~\"node\",sensor=~\"fan1\"}",
     "legendFormat": "CPU Fan"
    }
   ]
  },
  {
   "title": "GPU Utilization / Card",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 21 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "nvidia_gpu_duty_cycle", "legendFormat": "gpu{{minor_number}}" }
   ]
  },
  {
   "title": "GPU: Power Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "mwatt" }
   ],
   "targets": [
    {
     "expr": "nvidia_gpu_power_usage_milliwatts",
     "legendFormat": "gpu{{minor_number}}"
    }
   ]
  },
  {
   "title": "GPU: Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 28 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    { "expr": "nvidia_gpu_memory_used_bytes", "legendFormat": "gpu{{minor_number}}" }
   ]
  },
  {
   "title": "GPU Temp",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    { "expr": "nvidia_gpu_temperature_celsius", "legendFormat": "gpu{{minor_number}}" }
   ]
  },
  {
   "title": "GPU: Fan Speed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 35 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "nvidia_gpu_fanspeed_percent", "legendFormat": "gpu{{minor_number}}" }
   ]
  },
  {
   "title": "I/O Usage Read / Write",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "decbytes", "label": "Bytes read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=~\"192.168.96.40:9100\",device=~\"[a-z]*[a-z]\"}[5m])",
     "legendFormat": "{{device}} - Bytes read"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=~\"192.168.96.40:9100\",device=~\"[a-z]*[a-z]\"}[5m])",
     "legendFormat": "{{device}} - Bytes written"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "graph",
   "description": "Basic network info per interface",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 42 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~\"192.168.96.40:9100\",job=~\"node\",device=~\"eno1\"}[5m])",
     "legendFormat": "Received"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~\"192.168.96.40:9100\",job=~\"node\",device=~\"eno1\"}[5m])",
     "legendFormat": "Transmitted"
    }
   ]
  },
  { "title": "Garage Camera", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "CPU Basic",
   "type": "graph",
   "description": "Basic CPU info",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"system\",instance=~\"192.168.96.65:9100\",job=~\"node\"}[5m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='user',instance=~\"192.168.96.65:9100\",job=~\"node\"}[5m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='iowait',instance=~\"192.168.96.65:9100\",job=~\"node\"}[5m])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=~\".*irq\",instance=~\"192.168.96.65:9100\",job=~\"node\"}[5m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (irate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=~\"192.168.96.65:9100\",job=~\"node\"}[5m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"192.168.96.65:9100\",job=~\"node\"}[5m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "graph",
   "description": "Basic network info per interface",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 50 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~\"192.168.96.65:9100\",job=~\"node\"}[5m])",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~\"192.168.96.65:9100\",job=~\"node\"}[5m])",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  {
   "title": "I/O Usage Read / Write",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "decbytes", "label": "Bytes read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=~\"192.168.96.65:9100\"}[5m])",
     "legendFormat": "{{device}} - Bytes read"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=~\"192.168.96.65:9100\"}[5m])",
     "legendFormat": "{{device}} - Bytes written"
    }
   ]
  },
  {
   "title": "Hardware temperature monitor",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 58 },
   "yaxes": [
    { "format": "celsius", "label": "Temperature" }
   ],
   "targets": [
    {
     "expr": "rpi_cpu_temperature_celsius{instance=~\"192.168.96.65:9243\"}",
     "legendFormat": "Average Core Temperature"
    }
   ]
  },
  { "title": "Downstairs Camera", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "CPU Basic",
   "type": "graph",
   "description": "Basic CPU info",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"system\",instance=~\"192.168.96.70:9100\",job=~\"node\"}[5m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='user',instance=~\"192.168.96.70:9100\",job=~\"node\"}[5m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='iowait',instance=~\"192.168.96.70:9100\",job=~\"node\"}[5m])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=~\".*irq\",instance=~\"192.168.96.70:9100\",job=~\"node\"}[5m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (irate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=~\"192.168.96.70:9100\",job=~\"node\"}[5m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"192.168.96.70:9100\",job=~\"node\"}[5m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "graph",
   "description": "Basic network info per interface",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 66 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~\"192.168.96.70:9100\",job=~\"node\"}[5m])",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~\"192.168.96.70:9100\",job=~\"node\"}[5m])",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  {
   "title": "I/O Usage Read / Write",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "decbytes", "label": "Bytes read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=~\"192.168.96.70:9100\"}[5m])",
     "legendFormat": "{{device}} - Bytes read"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=~\"192.168.96.70:9100\"}[5m])",
     "legendFormat": "{{device}} - Bytes written"
    }
   ]
  },
  {
   "title": "Hardware temperature monitor",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 73 },
   "yaxes": [
    { "format": "celsius", "label": "Temperature" }
   ],
   "targets": [
    {
     "expr": "rpi_cpu_temperature_celsius{instance=~\"192.168.96.70:9243\"}",
     "legendFormat": "Average Core Temperature"
    }
   ]
  },
  { "title": "Upstairs Camera", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "CPU Basic",
   "type": "graph",
   "description": "Basic CPU info",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"system\",instance=~\"192.168.96.60:9100\",job=~\"node\"}[5m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='user',instance=~\"192.168.96.60:9100\",job=~\"node\"}[5m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='iowait',instance=~\"192.168.96.60:9100\",job=~\"node\"}[5m])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=~\".*irq\",instance=~\"192.168.96.60:9100\",job=~\"node\"}[5m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (irate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=~\"192.168.96.60:9100\",job=~\"node\"}[5m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"192.168.96.60:9100\",job=~\"node\"}[5m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "graph",
   "description": "Basic network info per interface",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 81 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~\"192.168.96.60:9100\",job=~\"node\"}[5m])",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~\"192.168.96.60:9100\",job=~\"node\"}[5m])",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  {
   "title": "I/O Usage Read / Write",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "decbytes", "label": "Bytes read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=~\"192.168.96.60:9100\"}[5m])",
     "legendFormat": "{{device}} -Bytes read"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=~\"192.168.96.60:9100\"}[5m])",
     "legendFormat": "{{device}} - Bytes written"
    }
   ]
  },
  {
   "title": "Hardware temperature monitor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 89 },
   "yaxes": [
    { "format": "celsius", "label": "Temperature" }
   ],
   "targets": [
    {
     "expr": "rpi_cpu_temperature_celsius{instance=~\"192.168.96.60:9243\"}",
     "legendFormat": "Average Core Temperature"
    }
   ]
  },
  { "title": "Pi-Hole", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 } },
  {
   "title": "CPU Basic",
   "type": "graph",
   "description": "Basic CPU info",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 98 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"system\",instance=~\"192.168.96.55:9100\",job=~\"node\"}[5m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='user',instance=~\"192.168.96.55:9100\",job=~\"node\"}[5m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='iowait',instance=~\"192.168.96.55:9100\",job=~\"node\"}[5m])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=~\".*irq\",instance=~\"192.168.96.55:9100\",job=~\"node\"}[5m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (irate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=~\"192.168.96.55:9100\",job=~\"node\"}[5m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"192.168.96.55:9100\",job=~\"node\"}[5m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "graph",
   "description": "Basic network info per interface",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 98 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~\"192.168.96.55:9100\",job=~\"node\"}[5m])",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~\"192.168.96.55:9100\",job=~\"node\"}[5m])",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  {
   "title": "I/O Usage Read / Write",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 106 },
   "yaxes": [
    { "format": "decbytes", "label": "Bytes read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=~\"192.168.96.55:9100\"}[5m])",
     "legendFormat": "{{device}} - Bytes read"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=~\"192.168.96.55:9100\"}[5m])",
     "legendFormat": "{{device}} - Bytes written"
    }
   ]
  },
  {
   "title": "Hardware temperature monitor",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 106 },
   "yaxes": [
    { "format": "celsius", "label": "Temperature" }
   ],
   "targets": [
    {
     "expr": "rpi_cpu_temperature_celsius{instance=~\"192.168.96.55:9243\"}",
     "legendFormat": "Average Core Temperature"
    }
   ]
  }
 ]
}