dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = RAW and block.createdate >= 2013-01-01 and block.createdate < 2013-02-01" > data_2013_jan_raw.blocks
dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = RECO and block.createdate >= 2013-01-01 and block.createdate < 2013-02-01" > data_2013_jan_reco.blocks
dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = AOD and block.createdate >= 2013-01-01 and block.createdate < 2013-02-01" > data_2013_jan_aod.blocks
dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = RAW-RECO and block.createdate >= 2013-01-01 and block.createdate < 2013-02-01" > data_2013_jan_raw-reco.blocks
dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = USER and block.createdate >= 2013-01-01 and block.createdate < 2013-02-01" > data_2013_jan_user.blocks
# 
dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = RAW and block.createdate >= 2013-02-01 and block.createdate < 2013-03-01" > data_2013_feb_raw.blocks
dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = RECO and block.createdate >= 2013-02-01 and block.createdate < 2013-03-01" > data_2013_feb_reco.blocks
dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = AOD and block.createdate >= 2013-02-01 and block.createdate < 2013-03-01" > data_2013_feb_aod.blocks
dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = RAW-RECO and block.createdate >= 2013-02-01 and block.createdate < 2013-03-01" > data_2013_feb_raw-reco.blocks
dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = USER and block.createdate >= 2013-02-01 and block.createdate < 2013-03-01" > data_2013_feb_user.blocks
# 
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = RAW and block.createdate >= 2013-03-01 and block.createdate < 2013-04-01" > data_2013_mar_raw.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = RECO and block.createdate >= 2013-03-01 and block.createdate < 2013-04-01" > data_2013_mar_reco.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = AOD and block.createdate >= 2013-03-01 and block.createdate < 2013-04-01" > data_2013_mar_aod.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = RAW-RECO and block.createdate >= 2013-03-01 and block.createdate < 2013-04-01" > data_2013_mar_raw-reco.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = USER and block.createdate >= 2013-03-01 and block.createdate < 2013-04-01" > data_2013_mar_user.blocks
# 
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = RAW and block.createdate >= 2013-04-01 and block.createdate < 2013-05-01" > data_2013_apr_raw.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = RECO and block.createdate >= 2013-04-01 and block.createdate < 2013-05-01" > data_2013_apr_reco.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = AOD and block.createdate >= 2013-04-01 and block.createdate < 2013-05-01" > data_2013_apr_aod.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = RAW-RECO and block.createdate >= 2013-04-01 and block.createdate < 2013-05-01" > data_2013_apr_raw-reco.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = USER and block.createdate >= 2013-04-01 and block.createdate < 2013-05-01" > data_2013_apr_user.blocks
# 
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = RAW and block.createdate >= 2013-05-01 and block.createdate < 2013-06-01" > data_2013_may_raw.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = RECO and block.createdate >= 2013-05-01 and block.createdate < 2013-06-01" > data_2013_may_reco.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = AOD and block.createdate >= 2013-05-01 and block.createdate < 2013-06-01" > data_2013_may_aod.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = RAW-RECO and block.createdate >= 2013-05-01 and block.createdate < 2013-06-01" > data_2013_may_raw-reco.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = USER and block.createdate >= 2013-05-01 and block.createdate < 2013-06-01" > data_2013_may_user.blocks
# 
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = RAW and block.createdate >= 2013-06-01 and block.createdate < 2013-07-01" > data_2013_jun_raw.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = RECO and block.createdate >= 2013-06-01 and block.createdate < 2013-07-01" > data_2013_jun_reco.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = AOD and block.createdate >= 2013-06-01 and block.createdate < 2013-07-01" > data_2013_jun_aod.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = RAW-RECO and block.createdate >= 2013-06-01 and block.createdate < 2013-07-01" > data_2013_jun_raw-reco.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = USER and block.createdate >= 2013-06-01 and block.createdate < 2013-07-01" > data_2013_jun_user.blocks
# 
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = RAW and block.createdate >= 2013-07-01 and block.createdate < 2013-08-01" > data_2013_jul_raw.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = RECO and block.createdate >= 2013-07-01 and block.createdate < 2013-08-01" > data_2013_jul_reco.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = AOD and block.createdate >= 2013-07-01 and block.createdate < 2013-08-01" > data_2013_jul_aod.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = RAW-RECO and block.createdate >= 2013-07-01 and block.createdate < 2013-08-01" > data_2013_jul_raw-reco.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = USER and block.createdate >= 2013-07-01 and block.createdate < 2013-08-01" > data_2013_jul_user.blocks
# 
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = RAW and block.createdate >= 2013-08-01 and block.createdate < 2013-09-01" > data_2013_aug_raw.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = RECO and block.createdate >= 2013-08-01 and block.createdate < 2013-09-01" > data_2013_aug_reco.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = AOD and block.createdate >= 2013-08-01 and block.createdate < 2013-09-01" > data_2013_aug_aod.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = RAW-RECO and block.createdate >= 2013-08-01 and block.createdate < 2013-09-01" > data_2013_aug_raw-reco.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = USER and block.createdate >= 2013-08-01 and block.createdate < 2013-09-01" > data_2013_aug_user.blocks

# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = RAW and block.createdate >= 2013-09-01 and block.createdate < 2013-10-01" > data_2013_sep_raw.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = RECO and block.createdate >= 2013-09-01 and block.createdate < 2013-10-01" > data_2013_sep_reco.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = AOD and block.createdate >= 2013-09-01 and block.createdate < 2013-10-01" > data_2013_sep_aod.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = RAW-RECO and block.createdate >= 2013-09-01 and block.createdate < 2013-10-01" > data_2013_sep_raw-reco.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = USER and block.createdate >= 2013-09-01 and block.createdate < 2013-10-01" > data_2013_sep_user.blocks

# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = RAW and block.createdate >= 2013-10-01 and block.createdate < 2013-11-01" > data_2013_oct_raw.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = RECO and block.createdate >= 2013-10-01 and block.createdate < 2013-11-01" > data_2013_oct_reco.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = AOD and block.createdate >= 2013-10-01 and block.createdate < 2013-11-01" > data_2013_oct_aod.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = RAW-RECO and block.createdate >= 2013-10-01 and block.createdate < 2013-11-01" > data_2013_oct_raw-reco.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = USER and block.createdate >= 2013-10-01 and block.createdate < 2013-11-01" > data_2013_oct_user.blocks

# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = RAW and block.createdate >= 2013-11-01 and block.createdate < 2013-12-01" > data_2013_nov_raw.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = RECO and block.createdate >= 2013-11-01 and block.createdate < 2013-12-01" > data_2013_nov_reco.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = AOD and block.createdate >= 2013-11-01 and block.createdate < 2013-12-01" > data_2013_nov_aod.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = RAW-RECO and block.createdate >= 2013-11-01 and block.createdate < 2013-12-01" > data_2013_nov_raw-reco.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = USER and block.createdate >= 2013-11-01 and block.createdate < 2013-12-01" > data_2013_nov_user.blocks
# 
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = RAW and block.createdate >= 2013-12-01 and block.createdate < 2014-01-01" > data_2013_dec_raw.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = RECO and block.createdate >= 2013-12-01 and block.createdate < 2014-01-01" > data_2013_dec_reco.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = AOD and block.createdate >= 2013-12-01 and block.createdate < 2014-01-01" > data_2013_dec_aod.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = RAW-RECO and block.createdate >= 2013-12-01 and block.createdate < 2014-01-01" > data_2013_dec_raw-reco.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = USER and block.createdate >= 2013-12-01 and block.createdate < 2014-01-01" > data_2013_dec_user.blocks


rm -f statistics.txt

cat data_2013_jan_raw.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting'  | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi 'express' | grep -v 'Interfill' | awk '{SUM1+=$2} {SUM2+=$3} END {print "January 2013 RAW: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2013_jan_reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptReco | awk '{SUM1+=$2} {SUM2+=$3} END {print "January 2013 PromptReco RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2013_jan_reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | awk '{SUM1+=$2} {SUM2+=$3} END {print "January 2013 PromptSkim RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2013_jan_reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | awk '{SUM1+=$2} {SUM2+=$3} END {print "January 2013 NonPrompt RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2013_jan_aod.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptReco | awk '{SUM1+=$2} {SUM2+=$3} END {print "January 2013 PromptReco AOD: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2013_jan_aod.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | awk '{SUM1+=$2} {SUM2+=$3} END {print "January 2013 PromptSkim AOD: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2013_jan_aod.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | awk '{SUM1+=$2} {SUM2+=$3} END {print "January 2013 NonPrompt AOD: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2013_jan_raw-reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | awk '{SUM1+=$2} {SUM2+=$3} END {print "January 2013 PromptSkim RAW-RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2013_jan_raw-reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | awk '{SUM1+=$2} {SUM2+=$3} END {print "January 2013 NonPrompt RAW-RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2013_jan_user.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | grep Run2013 | awk '{SUM1+=$2} {SUM2+=$3} END {print "January 2013 PromptSkim USER: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2013_jan_user.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | grep Run2013 | awk '{SUM1+=$2} {SUM2+=$3} END {print "January 2013 NonPrompt USER: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt

cat data_2013_feb_raw.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | awk '{SUM1+=$2} {SUM2+=$3} END {print "Feburary 2013 RAW: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2013_feb_reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptReco | awk '{SUM1+=$2} {SUM2+=$3} END {print "Feburary 2013 PromptReco RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2013_feb_reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | awk '{SUM1+=$2} {SUM2+=$3} END {print "Feburary 2013 PromptSkim RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2013_feb_reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | awk '{SUM1+=$2} {SUM2+=$3} END {print "Feburary 2013 NonPrompt RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2013_feb_aod.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptReco | awk '{SUM1+=$2} {SUM2+=$3} END {print "Feburary 2013 PromptReco AOD: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2013_feb_aod.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | awk '{SUM1+=$2} {SUM2+=$3} END {print "Feburary 2013 PromptSkim AOD: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2013_feb_aod.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | awk '{SUM1+=$2} {SUM2+=$3} END {print "Feburary 2013 NonPrompt AOD: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2013_feb_raw-reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | awk '{SUM1+=$2} {SUM2+=$3} END {print "Feburary 2013 PromptSkim RAW-RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2013_feb_raw-reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | awk '{SUM1+=$2} {SUM2+=$3} END {print "Feburary 2013 NonPrompt RAW-RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2013_feb_user.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | grep Run2013 | awk '{SUM1+=$2} {SUM2+=$3} END {print "Feburary 2013 PromptSkim USER: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2013_feb_user.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | grep Run2013 | awk '{SUM1+=$2} {SUM2+=$3} END {print "Feburary 2013 NonPrompt USER: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# 
# cat data_2013_mar_raw.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | awk '{SUM1+=$2} {SUM2+=$3} END {print "March 2013 RAW: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_mar_reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptReco | awk '{SUM1+=$2} {SUM2+=$3} END {print "March 2013 PromptReco RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_mar_reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | awk '{SUM1+=$2} {SUM2+=$3} END {print "March 2013 PromptSkim RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_mar_reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | awk '{SUM1+=$2} {SUM2+=$3} END {print "March 2013 NonPrompt RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_mar_aod.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptReco | awk '{SUM1+=$2} {SUM2+=$3} END {print "March 2013 PromptReco AOD: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_mar_aod.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | awk '{SUM1+=$2} {SUM2+=$3} END {print "March 2013 PromptSkim AOD: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_mar_aod.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | awk '{SUM1+=$2} {SUM2+=$3} END {print "March 2013 NonPrompt AOD: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_mar_raw-reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | awk '{SUM1+=$2} {SUM2+=$3} END {print "March 2013 PromptSkim RAW-RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_mar_raw-reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | awk '{SUM1+=$2} {SUM2+=$3} END {print "March 2013 NonPrompt RAW-RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_mar_user.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | grep Run2013 | awk '{SUM1+=$2} {SUM2+=$3} END {print "March 2013 PromptSkim USER: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_mar_user.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | grep Run2013 | awk '{SUM1+=$2} {SUM2+=$3} END {print "March 2013 NonPrompt USER: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# 
# cat data_2013_apr_raw.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | awk '{SUM1+=$2} {SUM2+=$3} END {print "April 2013 RAW: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_apr_reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptReco | awk '{SUM1+=$2} {SUM2+=$3} END {print "April 2013 PromptReco RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_apr_reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | awk '{SUM1+=$2} {SUM2+=$3} END {print "April 2013 PromptSkim RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_apr_reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | awk '{SUM1+=$2} {SUM2+=$3} END {print "April 2013 NonPrompt RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_apr_aod.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptReco | awk '{SUM1+=$2} {SUM2+=$3} END {print "April 2013 PromptReco AOD: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_apr_aod.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | awk '{SUM1+=$2} {SUM2+=$3} END {print "April 2013 PromptSkim AOD: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_apr_aod.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | awk '{SUM1+=$2} {SUM2+=$3} END {print "April 2013 NonPrompt AOD: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_apr_raw-reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | awk '{SUM1+=$2} {SUM2+=$3} END {print "April 2013 PromptSkim RAW-RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_apr_raw-reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | awk '{SUM1+=$2} {SUM2+=$3} END {print "April 2013 NonPrompt RAW-RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_apr_user.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | grep Run2013 | awk '{SUM1+=$2} {SUM2+=$3} END {print "April 2013 PromptSkim USER: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_apr_user.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | grep Run2013 | awk '{SUM1+=$2} {SUM2+=$3} END {print "April 2013 NonPrompt USER: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# 
# cat data_2013_may_raw.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | awk '{SUM1+=$2} {SUM2+=$3} END {print "May 2013 RAW: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_may_reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptReco | awk '{SUM1+=$2} {SUM2+=$3} END {print "May 2013 PromptReco RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_may_reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | awk '{SUM1+=$2} {SUM2+=$3} END {print "May 2013 PromptSkim RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_may_reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | awk '{SUM1+=$2} {SUM2+=$3} END {print "May 2013 NonPrompt RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_may_aod.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptReco | awk '{SUM1+=$2} {SUM2+=$3} END {print "May 2013 PromptReco AOD: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_may_aod.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | awk '{SUM1+=$2} {SUM2+=$3} END {print "May 2013 PromptSkim AOD: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_may_aod.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | awk '{SUM1+=$2} {SUM2+=$3} END {print "May 2013 NonPrompt AOD: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_may_raw-reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | awk '{SUM1+=$2} {SUM2+=$3} END {print "May 2013 PromptSkim RAW-RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_may_raw-reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | awk '{SUM1+=$2} {SUM2+=$3} END {print "May 2013 NonPrompt RAW-RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_may_user.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | grep Run2013 | awk '{SUM1+=$2} {SUM2+=$3} END {print "May 2013 PromptSkim USER: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_may_user.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | grep Run2013 | awk '{SUM1+=$2} {SUM2+=$3} END {print "May 2013 NonPrompt USER: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# 
# cat data_2013_jun_raw.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | awk '{SUM1+=$2} {SUM2+=$3} END {print "June 2013 RAW: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_jun_reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptReco | awk '{SUM1+=$2} {SUM2+=$3} END {print "June 2013 PromptReco RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_jun_reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | awk '{SUM1+=$2} {SUM2+=$3} END {print "June 2013 PromptSkim RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_jun_reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | awk '{SUM1+=$2} {SUM2+=$3} END {print "June 2013 NonPrompt RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_jun_aod.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptReco | awk '{SUM1+=$2} {SUM2+=$3} END {print "June 2013 PromptReco AOD: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_jun_aod.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | awk '{SUM1+=$2} {SUM2+=$3} END {print "June 2013 PromptSkim AOD: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_jun_aod.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | awk '{SUM1+=$2} {SUM2+=$3} END {print "June 2013 NonPrompt AOD: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_jun_raw-reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | awk '{SUM1+=$2} {SUM2+=$3} END {print "June 2013 PromptSkim RAW-RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_jun_raw-reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | awk '{SUM1+=$2} {SUM2+=$3} END {print "June 2013 NonPrompt RAW-RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_jun_user.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | grep Run2013 | awk '{SUM1+=$2} {SUM2+=$3} END {print "June 2013 PromptSkim USER: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_jun_user.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | grep Run2013 | awk '{SUM1+=$2} {SUM2+=$3} END {print "June 2013 NonPrompt USER: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# 
# cat data_2013_jul_raw.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | awk '{SUM1+=$2} {SUM2+=$3} END {print "July 2013 RAW: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_jul_reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptReco | awk '{SUM1+=$2} {SUM2+=$3} END {print "July 2013 PromptReco RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_jul_reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | awk '{SUM1+=$2} {SUM2+=$3} END {print "July 2013 PromptSkim RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_jul_reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | awk '{SUM1+=$2} {SUM2+=$3} END {print "July 2013 NonPrompt RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_jul_aod.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptReco | awk '{SUM1+=$2} {SUM2+=$3} END {print "July 2013 PromptReco AOD: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_jul_aod.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | awk '{SUM1+=$2} {SUM2+=$3} END {print "July 2013 PromptSkim AOD: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_jul_aod.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | awk '{SUM1+=$2} {SUM2+=$3} END {print "July 2013 NonPrompt AOD: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_jul_raw-reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | awk '{SUM1+=$2} {SUM2+=$3} END {print "July 2013 PromptSkim RAW-RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_jul_raw-reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | awk '{SUM1+=$2} {SUM2+=$3} END {print "July 2013 NonPrompt RAW-RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_jul_user.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | grep Run2013 | awk '{SUM1+=$2} {SUM2+=$3} END {print "July 2013 PromptSkim USER: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_jul_user.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | grep Run2013 | awk '{SUM1+=$2} {SUM2+=$3} END {print "July 2013 NonPrompt USER: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# 
# cat data_2013_aug_raw.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | awk '{SUM1+=$2} {SUM2+=$3} END {print "August 2013 RAW: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_aug_reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptReco | awk '{SUM1+=$2} {SUM2+=$3} END {print "August 2013 PromptReco RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_aug_reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | awk '{SUM1+=$2} {SUM2+=$3} END {print "August 2013 PromptSkim RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_aug_reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | awk '{SUM1+=$2} {SUM2+=$3} END {print "August 2013 NonPrompt RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_aug_aod.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptReco | awk '{SUM1+=$2} {SUM2+=$3} END {print "August 2013 PromptReco AOD: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_aug_aod.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | awk '{SUM1+=$2} {SUM2+=$3} END {print "August 2013 PromptSkim AOD: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_aug_aod.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | awk '{SUM1+=$2} {SUM2+=$3} END {print "August 2013 NonPrompt AOD: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_aug_raw-reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | awk '{SUM1+=$2} {SUM2+=$3} END {print "August 2013 PromptSkim RAW-RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_aug_raw-reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | awk '{SUM1+=$2} {SUM2+=$3} END {print "August 2013 NonPrompt RAW-RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_aug_user.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | grep Run2013 | awk '{SUM1+=$2} {SUM2+=$3} END {print "August 2013 PromptSkim USER: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_aug_user.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | grep Run2013 | awk '{SUM1+=$2} {SUM2+=$3} END {print "August 2013 NonPrompt USER: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# # 
# cat data_2013_sep_raw.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | awk '{SUM1+=$2} {SUM2+=$3} END {print "September 2013 RAW: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_sep_reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptReco | awk '{SUM1+=$2} {SUM2+=$3} END {print "September 2013 PromptReco RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_sep_reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | awk '{SUM1+=$2} {SUM2+=$3} END {print "September 2013 PromptSkim RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_sep_reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | awk '{SUM1+=$2} {SUM2+=$3} END {print "September 2013 NonPrompt RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_sep_aod.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptReco | awk '{SUM1+=$2} {SUM2+=$3} END {print "September 2013 PromptReco AOD: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_sep_aod.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | awk '{SUM1+=$2} {SUM2+=$3} END {print "September 2013 PromptSkim AOD: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_sep_aod.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | awk '{SUM1+=$2} {SUM2+=$3} END {print "September 2013 NonPrompt AOD: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_sep_raw-reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | awk '{SUM1+=$2} {SUM2+=$3} END {print "September 2013 PromptSkim RAW-RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_sep_raw-reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | awk '{SUM1+=$2} {SUM2+=$3} END {print "September 2013 NonPrompt RAW-RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_sep_user.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | grep Run2013 | awk '{SUM1+=$2} {SUM2+=$3} END {print "September 2013 PromptSkim USER: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_sep_user.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | grep Run2013 | awk '{SUM1+=$2} {SUM2+=$3} END {print "September 2013 NonPrompt USER: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# # 
# cat data_2013_oct_raw.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | awk '{SUM1+=$2} {SUM2+=$3} END {print "October 2013 RAW: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_oct_reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptReco | awk '{SUM1+=$2} {SUM2+=$3} END {print "October 2013 PromptReco RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_oct_reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | awk '{SUM1+=$2} {SUM2+=$3} END {print "October 2013 PromptSkim RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_oct_reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | awk '{SUM1+=$2} {SUM2+=$3} END {print "October 2013 NonPrompt RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_oct_aod.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptReco | awk '{SUM1+=$2} {SUM2+=$3} END {print "October 2013 PromptReco AOD: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_oct_aod.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | awk '{SUM1+=$2} {SUM2+=$3} END {print "October 2013 PromptSkim AOD: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_oct_aod.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | awk '{SUM1+=$2} {SUM2+=$3} END {print "October 2013 NonPrompt AOD: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_oct_raw-reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | awk '{SUM1+=$2} {SUM2+=$3} END {print "October 2013 PromptSkim RAW-RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_oct_raw-reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | awk '{SUM1+=$2} {SUM2+=$3} END {print "October 2013 NonPrompt RAW-RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_oct_user.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | grep Run2013 | awk '{SUM1+=$2} {SUM2+=$3} END {print "October 2013 PromptSkim USER: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_oct_user.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | grep Run2013 | awk '{SUM1+=$2} {SUM2+=$3} END {print "October 2013 NonPrompt USER: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# # 
# cat data_2013_nov_raw.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | awk '{SUM1+=$2} {SUM2+=$3} END {print "November 2013 RAW: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_nov_reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptReco | awk '{SUM1+=$2} {SUM2+=$3} END {print "November 2013 PromptReco RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_nov_reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | awk '{SUM1+=$2} {SUM2+=$3} END {print "November 2013 PromptSkim RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_nov_reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | awk '{SUM1+=$2} {SUM2+=$3} END {print "November 2013 NonPrompt RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_nov_aod.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptReco | awk '{SUM1+=$2} {SUM2+=$3} END {print "November 2013 PromptReco AOD: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_nov_aod.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | awk '{SUM1+=$2} {SUM2+=$3} END {print "November 2013 PromptSkim AOD: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_nov_aod.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | awk '{SUM1+=$2} {SUM2+=$3} END {print "November 2013 NonPrompt AOD: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_nov_raw-reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | awk '{SUM1+=$2} {SUM2+=$3} END {print "November 2013 PromptSkim RAW-RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_nov_raw-reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | awk '{SUM1+=$2} {SUM2+=$3} END {print "November 2013 NonPrompt RAW-RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_nov_user.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | grep Run2013 | awk '{SUM1+=$2} {SUM2+=$3} END {print "November 2013 PromptSkim USER: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_nov_user.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | grep Run2013 | awk '{SUM1+=$2} {SUM2+=$3} END {print "November 2013 NonPrompt USER: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# # 
# cat data_2013_dec_raw.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | awk '{SUM1+=$2} {SUM2+=$3} END {print "December 2013 RAW: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_dec_reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptReco | awk '{SUM1+=$2} {SUM2+=$3} END {print "December 2013 PromptReco RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_dec_reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | awk '{SUM1+=$2} {SUM2+=$3} END {print "December 2013 PromptSkim RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_dec_reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | awk '{SUM1+=$2} {SUM2+=$3} END {print "December 2013 NonPrompt RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_dec_aod.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptReco | awk '{SUM1+=$2} {SUM2+=$3} END {print "December 2013 PromptReco AOD: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_dec_aod.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | awk '{SUM1+=$2} {SUM2+=$3} END {print "December 2013 PromptSkim AOD: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_dec_aod.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | awk '{SUM1+=$2} {SUM2+=$3} END {print "December 2013 NonPrompt AOD: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_dec_raw-reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | awk '{SUM1+=$2} {SUM2+=$3} END {print "December 2013 PromptSkim RAW-RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_dec_raw-reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | awk '{SUM1+=$2} {SUM2+=$3} END {print "December 2013 NonPrompt RAW-RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_dec_user.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | grep Run2013 | awk '{SUM1+=$2} {SUM2+=$3} END {print "December 2013 PromptSkim USER: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2013_dec_user.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | grep Run2013 | awk '{SUM1+=$2} {SUM2+=$3} END {print "December 2013 NonPrompt USER: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# 
# 
